spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_clone
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyaway:
      enabled: false

    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/whatsapp-clone
            
      serverlet:
        multipart:
          max-file-size: 50MB
      
      application:
        file:
          uploads: 
            media-output.path: ./uploads